### ISSUE TITLE
banned-users not working

### ISSUE THREAD

**Issue by RoinujNosde** [fiso64/slsk-batchdl#88]
I'm running sldl like this:
`sldl "youtube url here" --max-album-track-count 30 --concurrent-downloads 10 --user myuser --pass mypass --path /music2 --no-progress -a --verbose --log-file /data/log.txt --failed-album-path 'delete' --strict-artist --banned-users some,banned,users`

But it seems to ignore the max-album-track-count, it tried to download a folder with 1000+ files in it.
It also tries to download from banned users.

**Comment by fiso64** [comment]
Album track count options are for album downloads.

I'll check again if banned users works.

**Comment by fiso64** [comment]
I just realized that album track count conditions do not apply after retrieving all files from the folder. It only checks the number of files in the initial search response. This becomes noticeable if you're searching for song names while downloading albums (like you are), because the search results will  only include that one song in every folder, but retrieving all files will give many more.

I'll have to think of a way to handle this.

**Comment by fiso64** [comment]
I have checked again and `--banned-users` should be working. Make sure that your list does not have any spaces (i.e `user1,user2` not `user1, user2`) and check the case matches, because soulseek usernames are case-sensitive.

**Comment by RoinujNosde** [comment]
>  Make sure that your list does not have any spaces (i.e `user1,user2` not `user1, user2`) and check the case matches, because soulseek usernames are case-sensitive.

I copied the usernames from sldl log, the case should be correct. I also double-checked on the soulseek client and was able to browse them.

There are no spaces between them.

**Comment by fiso64** [comment]
Can you try a very simple example like `sldl "artist - somealbum" -at`, check the first 3 users and then run again `sldl "artist - somealbum" -at --banned-users user1,user2,user3`? 

If this works then please provide the concrete youtube song url and the list of banned users which fails.

**Comment by RoinujNosde** [comment]
Couldn't reproduce the issue with `sldl "imagine dragons - evolve" -at`. Also tested on a smaller playlist (3 videos), no luck either.

I can still reproduce with this one:
`"https://www.youtube.com/watch?v=v8bUL0EKuHw&list=PLUxx9XxbPv4GmnhSf9D1-m0yY6nCCGKUS&pp=gAQB"`
`--banned-users mamaweasley,Wolfrine2538,gmarkos2,boa-noite,eddie2022,boanoite`
![Image](https://github.com/user-attachments/assets/7e1dd933-ccc4-493f-97d3-d209db62524a)
User `boanoite` is in the banned list, but it still showed up in the search.

**Comment by fiso64** [comment]
When I run
```
"https://www.youtube.com/watch?v=v8bUL0EKuHw&list=PLUxx9XxbPv4GmnhSf9D1-m0yY6nCCGKUS&pp=gAQB" -at --offset 86 -n 1 --banned-users mamaweasley,Wolfrine2538,gmarkos2,boanoite,eddie2022 --no-config --login a8sdasd9jasd;9asjda9sddj
```
the results do not include shares from that user and it works as expected. Does it work with this exact command?

**Comment by RoinujNosde** [comment]
This is the output:
![Screenshot_2025-03-26-15-35-57-34_61c78dc80ee02b53007c815fefe993e3.jpg](https://github.com/user-attachments/assets/beebc90e-b4a3-4bc0-b021-7fdf32b354a6)

Btw, --login didn't work, I replaced it with --user and --pass.

**Comment by fiso64** [comment]
Sorry, the command also needs `--no-skip-existing`

**Comment by RoinujNosde** [comment]
```
 sldl "https://www.youtube.com/watch?v=v8bUL0EKuHw&list=PLUxx9XxbPv4GmnhSf9D1-m0yY6nCCGKUS&pp=gAQB" -at --offset 86 -n 1 --banned-users mamaweasley,Wolfrine2538,gmarkos2,eddie2022,tuxx,JamesTran,Musicmaster2023,TauAs,rblotnicky --no-config --user a8sdasd9jasd --pass 9asjda9sddj --path /music2 --no-skip-existing
```

The filter worked. (Added other users to the banned list, it's a different song)

**Comment by fiso64** [comment]
In the latest release sldl will check album-track-count limits again after retrieving the full folder contents. Because this is comparatively slow it will only try this at most 3 times.

As for the banned users issue, I was unable to reproduce it.

**Comment by RoinujNosde** [comment]
Thanks!

> As for the banned users issue, I was unable to reproduce it.

I will let you know if I find a way to reproduce it.
